sudo: false
language: python
python:
  - "2.7"
  - "3.4.5"
  - "3.5.2"
install:
  - pip install --upgrade pip
  - pip install python-dateutil --upgrade
  - pip install pytz --upgrade
  - pip install tzlocal --upgrade
  - pip install cython --upgrade
  - pip install pymongo --upgrade
  - pip install numpy --upgrade
  - pip install pandas --upgrade
  - pip install decorator --upgrade
  - pip install enum34 --upgrade
  - pip install lz4 --upgrade
  - pip install mock --upgrade
  - pip install mockextras
  - pip install pytest --upgrade
  - pip install pytest-cov==2.3.0
  - pip install pytest-server-fixtures --upgrade
  - pip install pytest-timeout==1.0.0
  - pip install pytest-xdist==1.15.0
  - pip install setuptools-git --upgrade
script:
  - pip freeze
  - python setup.py test --pytest-args=-v
