dist: precise
sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
services:
   - mongodb

install:
  - mongo --version
  - pip install --upgrade pip
  - pip install python-dateutil --upgrade
  - pip install pytz --upgrade
  - pip install tzlocal --upgrade
  - pip install cython --upgrade
  - pip install pymongo --upgrade
  - pip install numpy --upgrade
  - pip install pandas --upgrade
  - pip install decorator --upgrade
  - pip install enum34 --upgrade
  - pip install lz4==0.8.2
  - pip install mock --upgrade
  - pip install mockextras
  - pip install pytest --upgrade
  - pip install pytest-cov --upgrade
  - pip install pytest-server-fixtures --upgrade
  - pip install pytest-timeout --upgrade
  - pip install pytest-xdist --upgrade
  - pip install setuptools-git --upgrade
script:
  - pip freeze
  - python setup.py test --pytest-args=-v
